name: 'Build Service Image'
description: 'Build a Traction Service Image'
inputs:
  context:
    required: true
    type: string
  image_name:
    required: true
    type: string
  token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2      
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner}}
        password: ${{ secrets.token }}

    - name: Prepare docker tags for holder image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ inputs.image_name }}
        tags: |
          type=ref,event=pr
          type=sha  

    - name: Build and push holder image
      id: builder
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}