name: 'Tag Image'
description: 'Tag a Traction Service Image'
inputs:
  tag:
    required: true
    type: string
  image_name:
    required: true
    type: string
  image_sha:
    required: true
    type: string
  token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2      

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner}}
        password: ${{ inputs.token }}

    - name: add tag to image
      shell: bash
      run: docker tag traction-holder:sha-${{ inputs.image_sha }} ghcr.io/${{ inputs.image_name }}:${{ inputs.tag }}