name: 'Tag Image'
description: 'Tag a Traction Service Image'
inputs:
  tag:
    required: true
    type: string
  image_name:
    required: true
    type: string
  image_sha:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Log in to registry
      shell: bash   
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      shell: bash   
      run: |
        IMAGE_ID=ghcr.io/${{ inputs.image_name }}

        docker tag $IMAGE_ID:sha-${{ inputs.image_sha }} $IMAGE_ID:${{ inputs.tag }}