name: update manifest repo
description: Update Manifest Repository
inputs:
  repository_key:
    required: true
    type: string
  repository:
    required: true
    type: string
  target:
    required: true
    type: string
    default: 'dev'
  holder_image_tag:
    required: false
    type: string
  verifier_image_tag:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out manifest repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.repository_key }}
        repository: ${{ inputs.repository }}
        path: manifest-repo

    - name: Set up git
      shell: bash
      run: |
        cd manifest-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Update holder image
      shell: bash
      if: inputs.holder_image_tag != null
      run: |
        cd manifest-repo
        yq eval '.holder.image.tag = "${{ inputs.holder_image_tag }}"' -i values-${{ inputs.target }}.yaml

    - name: Update verifier image
      shell: bash
      if: inputs.verifier_image_tag != null
      run: |
        cd manifest-repo
        yq eval '.verifier.image.tag = "${{ inputs.verifier_image_tag }}"' -i values-${{ inputs.target }}.yaml

    - name: Push config changes
      shell: bash
      run: |
        cd manifest-repo
        git commit -am "Update manifests for ${{ inputs.target }}"
        git push origin
