name: CI

on:

  push:
    branches: 
      - develop

    tags:
      - 'v*'
  
  pull_request:
    branches:
      - develop
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    
  init:
    runs-on: ubuntu-20.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      CI_IMAGE_SHA: ''
      CI_IS_PREVIEW: ${{ github.event_name == 'pull_request' }}
      CI_IS_RELEASE: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
      CI_IS_DEV: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v') }}
      CI_IS_TEST: false
      CI_IS_PROD: false
      CI_VERSION: ''
      CI_PRERELEASE: ''
      CI_BUILD: ''
      CD_CONFIG: 'workflow'
    steps:
      - name: Parse semver string
        if: ${{ fromJSON(env.CI_IS_RELEASE) }}
        continue-on-error: true
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'   

      - name: set version tag
        if: ${{ steps.semver_parser.outputs.fullversion != null }}
        run: |
          echo "CI_VERSION=${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}" >> $GITHUB_ENV
          echo "CI_IS_PROD=${{ steps.semver_parser.outputs.prerelease == null }}" >> $GITHUB_ENV
          echo "CI_IS_TEST=${{ steps.semver_parser.outputs.prerelease != null }}" >> $GITHUB_ENV
          echo "CI_PRERELEASE=${{ steps.semver_parser.outputs.prerelease }}" >> $GITHUB_ENV
          echo "CI_BUILD=${{ steps.semver_parser.outputs.build }}" >> $GITHUB_ENV

      - name: set cd config (preview)
        if: ${{ fromJSON(env.CI_IS_PREVIEW) }}
        run: |
          echo "CD_CONFIG=pr" >> $GITHUB_ENV

      - name: set cd config (dev)
        if: ${{ fromJSON(env.CI_IS_DEV) }}
        run: |
          echo "CD_CONFIG=dev" >> $GITHUB_ENV

      - name: set cd config (test)
        if: ${{ fromJSON(env.CI_IS_TEST) }}
        run: |
          echo "CD_CONFIG=${{ env.CI_PRERELEASE }}" >> $GITHUB_ENV

      - name: set cd config (prod)
        if: ${{ fromJSON(env.CI_IS_PROD) }}
        run: |
          echo "CD_CONFIG=prod" >> $GITHUB_ENV

      - name: set image sha
        run: echo "CI_IMAGE_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: print outputs
        run: |
          echo "CI_IMAGE_SHA: ${{ env.CI_IMAGE_SHA }}"
          echo "CI_IS_PREVIEW: ${{ env.CI_IS_PREVIEW }}"  
          echo "CI_IS_RELEASE: ${{ env.CI_IS_RELEASE }}"
          echo "CI_IS_DEV: ${{ env.CI_IS_DEV }}"  
          echo "CI_IS_TEST: ${{ env.CI_IS_TEST }}"  
          echo "CI_IS_PROD: ${{ env.CI_IS_PROD }}"  
          echo "CI_VERSION: ${{ env.CI_VERSION }}"  
          echo "CI_PRERELEASE: ${{ env.CI_PRERELEASE }}"  
          echo "CI_BUILD: ${{ env.CI_BUILD }}" 
          echo "CD_CONFIG: ${{ env.CD_CONFIG }}"

    outputs:
      image_sha: ${{ env.CI_IMAGE_SHA }}
      is_preview: ${{ env.CI_IS_PREVIEW }}
      is_release: ${{ env.CI_IS_RELEASE }}
      is_dev: ${{ env.CI_IS_DEV }}
      is_test: ${{ env.CI_IS_TEST }}
      is_prod: ${{ env.CI_IS_PROD }}
      cd_config: ${{ env.CD_CONFIG }}
      version_no: ${{ env.CI_VERSION }}
      prerelease: ${{ env.CI_PRERELEASE }}
      build_no: ${{ env.CI_BUILD }}

  qa_holder: 
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/actions/qa_service.yaml@develop
        needs: init
        if: ${{ fromJSON(needs.init.outputs.is_dev) || fromJSON(needs.init.outputs.is_preview) }}
        with:
          context: './services/holder'

  build_holder:
    uses: usingtechnology/do-app/.github/workflows/build_service.yaml@develop
    needs: init
    if: ${{ fromJSON(needs.init.outputs.is_dev) || fromJSON(needs.init.outputs.is_preview) }}
    with:
      context: './services/holder'
      image_name: usingtechnology/do-app/traction-holder
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build_verifier:
    uses: usingtechnology/do-app/.github/workflows/build_service.yaml@develop
    needs: init
    if: ${{ fromJSON(needs.init.outputs.is_dev) || fromJSON(needs.init.outputs.is_preview) }}
    with:
      context: './services/verifier'
      image_name: usingtechnology/do-app/traction-verifier
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}


  update_config:
    runs-on: ubuntu-20.04
    needs: 
      - init
      - build_holder
      - build_verifier
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    
    steps:  
      - name: Check out config repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}

      - name: Update image ID and commit change
        shell: bash
        run: |
          ls -l
          yq eval '.holder.image.tag = "${{ needs.init.outputs.image_sha }}"' -i values-${{ needs.init.outputs.cd_config }}.yaml
          yq eval '.verifier.image.tag = "${{ needs.init.outputs.image_sha }}"' -i values-${{ needs.init.outputs.cd_config }}.yaml
          cat values-${{ needs.init.outputs.cd_config }}.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update image tags for ${{ needs.init.outputs.cd_config }}"
          git push origin




