name: CI

on:

  push:
    branches: 
      - develop

    tags:
      - 'v*'
  
  pull_request:
    branches:
      - develop
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    
  init:
    runs-on: ubuntu-20.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      CI_IMAGE_SHA: ${GITHUB_SHA::7}
      CI_IS_DEV: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v') }}
      CI_IS_RELEASE: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
      CI_IS_TEST: false
      CI_IS_PROD: false
      CI_IS_PREVIEW: ${{ github.event_name == 'pull_request' }}
      CI_VERSION: ''
      CI_PRERELEASE: ''
    steps:
      - name: Parse semver string
        if: ${{ fromJSON(env.CI_IS_RELEASE) }}
        continue-on-error: true
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'   

      - name: set version tag
        if: ${{ steps.semver_parser.outputs.fullversion != null }}
        run: |
          echo "CI_VERSION=${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}" >> $GITHUB_ENV
          echo "CI_IS_PROD=true" >> $GITHUB_ENV

      - name: set prerelease tag 
        if: ${{ steps.semver_parser.outputs.prerelease != null }}
        run: |
          echo "CI_PRERELEASE=${{ steps.semver_parser.outputs.prerelease }}" >> $GITHUB_ENV
          echo "CI_IS_TEST=true" >> $GITHUB_ENV
          echo "CI_IS_PROD=false" >> $GITHUB_ENV


      - name: print env
        run: env     