name: echo
on:
  push:
    branches: 
      - develop
    paths-ignore:
      - '.github/**'
    tags:
      - '*'

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: "set short_sha"
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: "set cd_target (dev)"
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: echo "cd_target=dev" >> $GITHUB_ENV
      
      - name: check release tag
        run: echo "is_release=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}" >> $GITHUB_ENV
      
      - name: Parse semver string
        if: ${{ fromJSON(env.is_release) }}
        continue-on-error: true
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'   
          
      - name: Use parsed semver
        run: |
            echo "${{ steps.semver_parser.outputs.major }}"
            echo "${{ steps.semver_parser.outputs.minor }}"
            echo "${{ steps.semver_parser.outputs.patch }}"
            echo "${{ steps.semver_parser.outputs.prerelease }}"
            echo "${{ steps.semver_parser.outputs.build }}"
            echo "${{ steps.semver_parser.outputs.fullversion }}"
            
      - name: "set cd_target (test)"
        if: ${{ fromJSON(env.is_release) }} && ${{ fromJSON(steps.semver_parser.outputs.prerelease) }}
        run: echo "cd_target=${{ steps.semver_parser.outputs.prerelease }}" >> $GITHUB_ENV
 
      - name: "set cd_target (prod)"
        if: ${{ fromJSON(env.is_release) }} && !${{ fromJSON(steps.semver_parser.outputs.prerelease) }}
        run: echo "cd_target=prod" >> $GITHUB_ENV
    
      - name: "set cd_target (none)"
        if: github.event_name == 'workflow_dispatch'
        run: echo "cd_target=none" >> $GITHUB_ENV
    
    outputs:
      short_sha: ${{ env.short_sha }}
      cd_target: ${{ env.cd_target }}
    
    
  echo:
     # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: init
    steps:
      - name: echo outputs
        run: |
            echo "${{needs.init.outputs.short_sha }}"
            echo "${{needs.init.outputs.cd_target }}"
