name: echo
on:
  push:
    branches: 
      - develop
    paths-ignore:
      - '.github/**'
    tags:
      - '*'

  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: "set short_sha"
        run: echo '::set-output name=short_sha::${GITHUB_SHA::7}'

      - name: "set cd_target (dev)"
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: echo '::set-output name=cd_target::dev'
        
      - name: Parse semver string
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: Use parsed semver
        run: |
            echo "v${{ steps.semver_parser.outputs.major }}"
            echo "v${{ steps.semver_parser.outputs.minor }}"
            echo "v${{ steps.semver_parser.outputs.patch }}"
            echo "v${{ steps.semver_parser.outputs.prerelease }}"
            echo "v${{ steps.semver_parser.outputs.build }}"
            echo "v${{ steps.semver_parser.outputs.fullversion }}"        

      - name: "set cd_target (test)"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && ${{ steps.semver_parser.outputs.prerelease }}
        run: echo '::set-output name=cd_target::${{ steps.semver_parser.outputs.prerelease }}'
 
      - name: "set cd_target (prod)"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !${{ steps.semver_parser.outputs.prerelease }} && {{ steps.semver_parser.outputs.fullversion }}
        run: echo '::set-output name=cd_target::prod'
     
  echo:
     # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: init
    steps:
      - name: echo outputs
        run: |
            echo "${{needs.init.outputs.short_sha }}"
            echo "${{needs.init.outputs.cd_target }}"
