name: echo
on:
  push:
    branches: 
      - develop
    paths-ignore:
      - '.github/**'
    tags:
      - '*'
    
  release:
    
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: "echo github.sha"
        run: echo ${{ github.sha }}
      - name: "echo github.sha short"
        run: echo ${GITHUB_SHA::7}
      - name: "echo github.ref"
        run: echo ${{ github.ref }}
      - name: "echo github.event_name"
        run: echo ${{ github.event_name }}
        
