name: inspect
on:
  push:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-20.04
    steps:
      - name: show env
        run: env
      - name: show context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"