name: inspect
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-20.04
    steps:
      - name: show env
        run: env
      - name: show github
        run: echo ${{ fromJson(toJson(github)) }}
