name: Push Services to Develop
on:
  push:
    branches: 
      - develop
    paths:
      - 'services/**'

jobs:

  build_holder:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2  
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - './services/holder/**'          
      - name: Build service
        if: steps.changes.outputs.src == 'true'
        uses: ./.github/actions/build_service
        id: builder
        with:
          context: './services/holder'
          image_name: ${{ github.repository_owner}}/holder_image
          registry: ghcr.io
          registry_username: ${{ github.actor}}          
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  build_verifier:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2  
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - './services/verifier/**'          
      - name: Build service
        if: steps.changes.outputs.src == 'true'
        uses: ./.github/actions/build_service
        id: builder
        with:
          context: './services/verifier'
          image_name: ${{ github.repository_owner}}/verifier_image
          registry: ghcr.io
          registry_username: ${{ github.actor}}          
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}
      image_version: ${{ steps.builder.outputs.image_version }}
      buildtime: ${{ steps.builder.outputs.buildtime }}

  update_config:
    runs-on: ubuntu-20.04
    needs: 
      - build_holder
      - build_verifier
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    
    steps:  
      - uses: actions/checkout@v2  

      - name: print outputs
        run: |
          echo "build_holder.image_tag: ${{ needs.build_holder.outputs.image_tag }}"
          echo "build_holder.image_version: ${{ needs.build_holder.outputs.image_version }}"
          echo "build_holder.buildtime: ${{ needs.build_holder.outputs.buildtime }}"
          echo "build_verifier.image_tag: ${{ needs.build_verifier.outputs.image_tag }}"
          echo "build_verifier.image_version: ${{ needs.build_verifier.outputs.image_version }}"
          echo "build_verifier.buildtime: ${{ needs.build_verifier.outputs.buildtime }}"

      - name: Update manifests
        uses: ./.github/actions/update_manifest_repo
        with:
          holder_image_tag: ${{ needs.build_holder.outputs.image_tag }}
          verifier_image_tag: ${{ needs.build_verifier.outputs.image_tag }}





