name: Promote Instance
on:
  push:
    tags:
      - 'v*'

jobs:    
  init:
    name: Set promotion values
    runs-on: ubuntu-20.04
    env:
      CI_IS_TEST: false
      CI_IS_PROD: false
      CI_VERSION: ''
      CI_PRERELEASE: ''
      PROMOTE_TO: 'test'
      PROMOTE_FROM: 'dev'
    steps:
      - name: Parse semver string
        continue-on-error: true
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'   

      - name: set version tag
        if: ${{ steps.semver_parser.outputs.fullversion != null }}
        run: |
          echo "CI_VERSION=${{ steps.semver_parser.outputs.fullversion }}" >> $GITHUB_ENV
          echo "CI_IS_PROD=${{ steps.semver_parser.outputs.prerelease == null }}" >> $GITHUB_ENV
          echo "CI_IS_TEST=${{ steps.semver_parser.outputs.prerelease != null }}" >> $GITHUB_ENV
          echo "CI_PRERELEASE=${{ steps.semver_parser.outputs.prerelease }}" >> $GITHUB_ENV
  
      - name: set cd config (test)
        if: ${{ fromJSON(env.CI_IS_TEST) }}
        run: |
          echo "PROMOTE_TO=test" >> $GITHUB_ENV
          echo "PROMOTE_FROM=dev" >> $GITHUB_ENV

      - name: set cd config (prod)
        if: ${{ fromJSON(env.CI_IS_PROD) }}
        run: |
          echo "PROMOTE_TO=prod" >> $GITHUB_ENV
          echo "PROMOTE_FROM=test" >> $GITHUB_ENV

      - name: print outputs
        run: |
          echo "PROMOTE_FROM: ${{ env.PROMOTE_FROM }}"
          echo "PROMOTE_TO: ${{ env.PROMOTE_TO }}"
          echo "CI_VERSION: ${{ env.CI_VERSION }}"  
          echo "CI_PRERELEASE: ${{ env.CI_PRERELEASE }}"

    outputs:
      promote_from: ${{ env.PROMOTE_FROM }}
      promote_to: ${{ env.PROMOTE_TO }}
      version: ${{ env.CI_VERSION }}

  update_config:
    name: Update manifests
    runs-on: ubuntu-20.04
    needs: 
      - init
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}

    steps:
      - uses: actions/checkout@v2

      - name: Read repo
        id: read_repo
        uses: ./.github/actions/read_manifest_repo
        with:
          target: ${{ needs.init.outputs.promote_from }}
          repository_key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }} 

      - name: Update repo
        uses: ./.github/actions/update_manifest_repo
        with:
          target: ${{ needs.init.outputs.promote_to }}
          repository_key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
          release_version: ${{ needs.init.outputs.version }}
          holder_image_tag: ${{ steps.read_repo.outputs.holder_image_tag }}
          holder_image_version: ${{ steps.read_repo.outputs.holder_image_version }}
          holder_image_buildtime: ${{ steps.read_repo.outputs.holder_image_buildtime }}
          verifier_image_tag: ${{ steps.read_repo.outputs.verifier_image_tag }}
          verifier_image_version: ${{ steps.read_repo.outputs.verifier_image_version }}
          verifier_image_buildtime: ${{ steps.read_repo.outputs.verifier_image_buildtime }}
