# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: 
      - develop
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - develop
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  tag: "dev"

jobs:
    
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: "set pr environment variables"
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=tag::pr"
      - name: "set test environment variables"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/test')
        run: echo "::set-env name=tag::test"
      - name: "set prod environment variables"
        if: github.event_name == 'push' && github.push.ref == 'refs/heads/main'
        run: echo "::set-env name=tag::prod"
          
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

  build-holder:
     # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: checkout
    
    steps:
      - name: Run a one-line script
        run: echo Hello, holder! Do stuff in ${env:tag}
        
  build-verifier:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: checkout 
    
    steps:
      - name: Run a one-line script
        run: echo Hello, verifier!

