# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: 
      - develop
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - develop
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: "set pr environment variables"
        if: github.event_name == 'pull_request'
        run: echo "tag=pr" >> $GITHUB_ENV
      - name: "set dev environment variables"
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: echo "tag=dev" >> $GITHUB_ENV
      - name: "set test environment variables"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/test')
        run: echo "tag=test" >> $GITHUB_ENV
      - name: "set prod environment variables"
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "tag=prod" >> $GITHUB_ENV
          
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
         

  build-holder:
     # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: init
    
    steps:
      - name: Run a one-line script
        run: echo Hello, holder! Do stuff in ${{ jobs.init.env.tag }}

      - name: Build and push holder image
        uses: docker/build-push-action@v2
        with:
          context: ./services/holder
          push: true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha
            type=raw,value=${{ jobs.init.env.tag }}
      
  build-verifier:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: init 
    
    steps:
      
      - name: Build and push verifier image
        uses: docker/build-push-action@v2
        with:
          context: ./services/verifier
          push: true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha
            type=raw,value=${{ jobs.init.env.tag }}


